# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/c1be35a1-af62-468e-979c-2785d524a09d/transcription
Content-Type: application/json

{
  "prompt": "reprocessar, tabela"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "c1be35a1-af62-468e-979c-2785d524a09d",
  "temperature": 0,
  "prompt": "Gere um resumo sucinto da transcrição do video informada a seguir: '''{transcription}''' "
}